### ISSUE TITLE
sass generierung verbessern

### ISSUE THREAD

**Issue by DO1JLR** [c3woc/c3woc-website#30]
schöner geht immer!

**Comment by maxbachmann** [comment]
was passt dir an der Sass Generierung denn aktuell noch nicht? das ist doch compressed -> mir ist unklar was daran schöner werden soll ;)

**Comment by DO1JLR** [comment]
@maxbachmann Das Issue kommt noch aus der Zeit, als es noch kein Plugin dafür gab.

Ist mit #31 gefixt.

**Comment by maxbachmann** [comment]
Ah ok
