### ISSUE TITLE
Flüssigkeit beim veganen Rezept unlogisch

### ISSUE THREAD

**Issue by fiee** [c3woc/c3woc-website#55]
Warum braucht ihr von der Hafermilch nur halb soviel wie von der Mandelmilch? (Und die Maßeinheiten fehlen da.)

**Comment by DO1JLR** [comment]
danke, guter hinweis. ist korrigiert

**Comment by jaid33** [comment]
Steht immernoch so auf der Seite: _Mandelmilch: 400 ml (alternativ 200 g Hafermilch)_  
https://c3woc.de/rezept/vegan/
